main: me.haffel.regeln.Main
name: Regeln
version: 1.0
author: Haffel

commands:
  rules:
    description: Regeln Befehl

permissions:
  rules.*:
    description: Zugang zu allen Befehlen des Regeln Plugins
    children:
      rules.move: true
      rules.reload: true
  rules.move:
    description: Erlaubt dir zu bestimmen ob man sich bewegen darf bevor man die Regeln akzeptiert hat.
    default: false
  rules.reload:
    description: Erlaubt dir die Config neu zu laden.
    default: false